name: CI
# edited in feature
on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
    build:
        name: Call Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/giddi-shravyagiddi-shravya/SonarCloud
            azure-pipeline-name: 'SonarDemo (4)'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}
